### ISSUE TITLE
Is there a printable version?

### ISSUE THREAD

**Issue by maximaleffekt** [jan-Ne/lipu-lili-pona#49]
Hey there, I really like this site and it looks like the two "pages" would be easy to print on a sheet of A4 paper. I have tried loading and printing the site in Firefox and Safari, but both have issues correctly formatting it. I have also manually edited the HTML a bit to try and convince the browsers to print it correctly, but that didn't work either.

Is there any interest from the creators to make an easily printable version of these pages, or is there one that I have missed?

**Comment by qupufu** [comment]
You can click the pdf button to find the printable pdf. I'll link it here also, though I don't know if you still need it, seeing as this issue is a couple months old. There's only a pdf for English for what I've found, so more should probably be made.

https://jan-ne.github.io/lipu-lili-pona/lipu_lili_pona_en.pdf
